[phases.setup]
nixPkgs = ["python310", "ffmpeg"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "python3.10 -m pip install --upgrade pip",
  "python3.10 -m pip install -r requirements.txt"
]

[start]
cmd = "python3.10 main.py"
