[phases.setup]
nixPkgs = ["python310", "ffmpeg"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python -m pip install -U pip",
    "python -m pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
